server:
  port: 9000

spring:
  application:
    name: api-gateway
    cloud:
      gateway:
        routes:
          - id: member-service
            predicates:
              - Path=/member-service/**
            uri: lb://member-service
            filters:
              - RewritePath=/member-service/(?<pathVar>.*), /$\{pathVar} # /member-service/get -> /get 으로 바뀌는 filter
          - id: order-service
            predicates:
              - Path=/order-service/**
            uri: lb://order-service
            filters:
              - RewritePath=/order-service/(?<pathVar>.*), /$\{pathVar} # /order-service/get -> /get 으로 바뀌는 filter

# Eureka
eureka:
  instance:
    hostname: 127.0.0.1
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://127.0.0.1:8088/eureka/}
    register-with-eureka: true
    fetch-registry: true