server:
  port: 9000

spring:
  application:
    name: api-gateway

# Eureka
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8088/eureka
    register-with-eureka: true
    fetch-registry: true