server:
  port: 9000

spring:
  application:
    name: api-gateway
    cloud:
      gateway:
        routes:
          - id: first-service
            predicates:
              - Path=/member-service/**
            uri: lb://member-service
          - id: second-service
            predicates:
              - Path=/order-service/**
            uri: lb://MEMBER-SERVICE

# Eureka
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8088/eureka
    register-with-eureka: true
    fetch-registry: true